---
name: 'Trigger: Push action'

on:
  push:
    branches:
      - '**'

jobs:
  acap:
    name: Build ACAP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armv7hf, aarch64]
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v2
        with:
          build-args: ARCH=${{ matrix.arch }}
          push: false
